apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-plugin-config
  namespace: dev-plugin
  labels:
    app: dev-plugin
    component: backend
    environment: production
data:
  NODE_ENV: "production"
  SERVER_PORT: "3000"
  MONITORING_ENABLED: "true"
  LOG_LEVEL: "info"
  CORS_ORIGINS: "https://app.example.com,https://admin.example.com"
  REDIS_HOST: "redis-service.dev-plugin.svc.cluster.local"
  REDIS_PORT: "6379"
  POSTGRES_HOST: "postgres-service.dev-plugin.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "devplugin"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-plugin-config
  namespace: dev-plugin-staging
  labels:
    app: dev-plugin
    component: backend
    environment: staging
data:
  NODE_ENV: "staging"
  SERVER_PORT: "3000"
  MONITORING_ENABLED: "true"
  LOG_LEVEL: "debug"
  CORS_ORIGINS: "https://staging.example.com,https://admin-staging.example.com"
  REDIS_HOST: "redis-service.dev-plugin-staging.svc.cluster.local"
  REDIS_PORT: "6379"
  POSTGRES_HOST: "postgres-service.dev-plugin-staging.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "devplugin_staging"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-plugin-config
  namespace: dev-plugin-dev
  labels:
    app: dev-plugin
    component: backend
    environment: development
data:
  NODE_ENV: "development"
  SERVER_PORT: "3000"
  MONITORING_ENABLED: "true"
  LOG_LEVEL: "debug"
  CORS_ORIGINS: "http://localhost:3000,http://localhost:5173"
  REDIS_HOST: "redis-service.dev-plugin-dev.svc.cluster.local"
  REDIS_PORT: "6379"
  POSTGRES_HOST: "postgres-service.dev-plugin-dev.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "devplugin_dev"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: dev-plugin
  labels:
    app: dev-plugin
    component: database
data:
  init.sql: |
    -- Create additional schemas if needed
    -- CREATE SCHEMA IF NOT EXISTS audit;

    -- Create extensions
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
    CREATE EXTENSION IF NOT EXISTS "pg_stat_statements";

    -- Set up monitoring
    -- ALTER SYSTEM SET log_statement = 'all';
    -- SELECT pg_reload_conf();
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: dev-plugin
  labels:
    app: dev-plugin
    component: cache
data:
  redis.conf: |
    # Redis configuration
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    save 900 1
    save 300 10
    save 60 10000